views.filter.avportal_text_search:
  type: views.filter.string
  label: 'AV Portal Search'

entity_browser.browser.widget.avportal_search:
  type: entity_browser.browser.widget.view
  label: 'AV Portal widget configuration'
